# Generated by Django 5.1.4 on 2025-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livres_images/')),
                ('date_naissance', models.DateField()),
                ('poste', models.CharField(max_length=200)),
                ('equipe', models.CharField(max_length=100)),
            ],
        ),
    ]
